### ISSUE TITLE
Arduino Library Structure

### ISSUE THREAD

**Issue by unref-ptr** [laith-dosinfection/lwIOlinkMaster#5]
For a future release I think it would be convenient to restructure the project as a library instead of a platform IO project, and add an example folder with the  test code. This allows to create releases and download automatically the library.

**Comment by laith-dosinfection** [comment]
Attempted the requested restructure currently in test branch.  @unref-ptr would you mind verifying it is structured correctly?

**Comment by unref-ptr** [comment]
I will check it out. I also think the library can be verified through ci-cd. Arduino has a tool to validate library folder struct and files.
