### ISSUE TITLE
HW Sink current wakeup

### ISSUE THREAD

**Issue by unref-ptr** [laith-dosinfection/lwIOlinkMaster#9]
I did not find it on the current project readme but just wanted to point out that for the TIOL112, a sink current is required for the wakeup procedure.

There is an [application note from TI](https://www.ti.com/lit/ug/tidueb8c/tidueb8c.pdf) and also this article from [Analog Devices.](https://www.analog.com/en/technical-articles/configuring-an-iolink-device-transceiver-for-use-in-an-iolink-master.html)

**Comment by laith-dosinfection** [comment]
From what I understand the TIOL112 does not require those external components for the wakeup procedure.  Only the tiol111.

You referenced TI's older design for an io link master the new one is [here](https://www.ti.com/tool/TIDA-010234).

<img width="769" alt="image" src="https://github.com/laith-dosinfection/lwIOlinkMaster/assets/83931086/559ac015-80a4-40a0-ba7e-387f2c547921">

I couldn't find it in the spec sheet but I could find it in the hardware design file for the newer TI IO-link master reference design.  Either way my hardware design already incorporates the footprint for the sink so it should be compatible with both.  However, the code should be able to be validated on the [tiol112 eval board](https://www.ti.com/lit/ug/sllu344/sllu344.pdf)

**Comment by unref-ptr** [comment]
nice catch, yes I got confused between both models.
